### ISSUE TITLE
openapi fails when plugin is enabled.

### ISSUE THREAD

**Issue by ThomasADavis** [mattieserver/netbox-topology-views#295]
### NetBox version

v3.5.1

### Topology Views version

latest

### Steps to Reproduce

Install plugin.
Enable plugin.  No other plugin is enabled.
Enable netbox debug (only way to see stack dump)
goto $NETBOX_URL/api/schema/swagger-ui/

### Expected Behavior

doesn't crash openapi.

### Observed Behavior

get error message:

```Failed to load API definition.
Errors
Hide
 
Fetch error
Internal Server Error /api/schema```

netbox log has this message:

```Internal Server Error: /api/schema/
Traceback (most recent call last):
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/exception.py", line 56, in inner
    response = get_response(request)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/core/handlers/base.py", line 197, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/decorators/csrf.py", line 55, in wrapped_view
    return view_func(*args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/django/views/generic/base.py", line 103, in view
    return self.dispatch(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/views.py", line 509, in dispatch
    response = self.handle_exception(exc)
  File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/views.py", line 469, in handle_exception
    self.raise_uncaught_exception(exc)
  File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/views.py", line 480, in raise_uncaught_exception
    raise exc
  File "/opt/netbox/venv/lib/python3.10/site-packages/rest_framework/views.py", line 506, in dispatch
    response = handler(request, *args, **kwargs)
  File "/opt/netbox/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 83, in get
    return self._get_schema_response(request)
  File "/opt/netbox/venv/lib/python3.10/site-packages/drf_spectacular/views.py", line 91, in _get_schema_response
    data=generator.get_schema(request=request, public=self.serve_public),
  File "/opt/netbox/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 268, in get_schema
    paths=self.parse(request, public),
  File "/opt/netbox/venv/lib/python3.10/site-packages/drf_spectacular/generators.py", line 239, in parse
    operation = view.schema.get_operation(
  File "/opt/netbox/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 83, in get_operation
    request_body = self._get_request_body()
  File "/opt/netbox/netbox/core/api/schema.py", line 191, in _get_request_body
    return super()._get_request_body(direction)
  File "/opt/netbox/venv/lib/python3.10/site-packages/drf_spectacular/openapi.py", line 1247, in _get_request_body
    request_serializer = self.get_request_serializer()
  File "/opt/netbox/netbox/core/api/schema.py", line 103, in get_request_serializer
    writable_class = self.get_writable_class(serializer)
  File "/opt/netbox/netbox/core/api/schema.py", line 146, in get_writable_class
    for child_name, child in fields.items():
AttributeError: 'cached_property' object has no attribute 'items'
10.42.1.22 - - [11/May/2023:19:05:38 +0000] "GET /api/schema/ HTTP/1.1" 500 162079 "https://netbox-dev.nersc.gov/api/schema/swagger-ui/" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36"
```

**Comment by mattieserver** [comment]
I noted this to, will see if i can create a new release.
It currently dont have much time so it might be somewhere next week (or a bit later).

**Comment by ThomasADavis** [comment]
No rush, we aren't ready to upgrade the production instance to v3.5..  There are other issues we need to solve first.

**Comment by kirillmuravyev** [comment]
facing the same issue here after upgrading from Netbox v3.4.8 to v3.5.2

**Comment by mattieserver** [comment]
I have time to look into this next week so if you need the swagger/openapi before then it's probably best to disable the plugin until then.

**Comment by misch42** [comment]
I installed version 3.6.1b1. API is working again. Thanks.

Michael.
