### ISSUE TITLE
Plugin incompatible with netbox 3.5

### ISSUE THREAD

**Issue by Trusthier** [mattieserver/netbox-topology-views#281]
### NetBox version

V3.5

### Topology Views version

V3.3

### Steps to Reproduce

1. upgrade 3.4.9 to 3.5

### Expected Behavior

The plugin should have no problem when running upgrade.sh

### Observed Behavior

   from . import views
  File "/opt/netbox/venv/lib64/python3.8/site-packages/netbox_topology_views/views.py", line 33, in <module>
    from netbox_topology_views.forms import DeviceFilterForm, IndividualOptionsForm
  File "/opt/netbox/venv/lib64/python3.8/site-packages/netbox_topology_views/forms.py", line 16, in <module>
    from utilities.forms import (
ImportError: cannot import name 'TagFilterField' from 'utilities.forms' (/opt/netbox/netbox/utilities/forms/__init__.py)

**Comment by mattieserver** [comment]
The import has changed for v3.5
from `utilities.forms` to `utilities.forms.fields`

So you are right, the plugin does not work on v3.5.
I will see if i can create a new release later today.

**Comment by Trusthier** [comment]
Nothing urgent I'm staying in 3.4.9, your plugin is more than necessary. Thanks for the feedback and the work!
