### ISSUE TITLE
'CircuitTermination' object has no attribute 'provider_network'

### ISSUE THREAD

**Issue by NordloSydost-Pajje** [mattieserver/netbox-topology-views#593]
### NetBox version

4.2.1

### Topology Views version

4.2.0

### Steps to Reproduce

Display topology

### Expected Behavior

Topology to be displayed.

### Observed Behavior

<class 'AttributeError'>

'CircuitTermination' object has no attribute 'provider_network'

Python version: 3.10.12
NetBox version: 4.2.1
Plugins: 
  netbox_ipcalculator: 1.4.9
  netbox_lists: 4.0.1
  netbox_topology_views: 4.2.0

**Comment by ibuclaw** [comment]
Workaround is to untick "Show Circuit Terminations" for now.

**Comment by mattieserver** [comment]
How does your circuit look like? Both terminations on an interface?

**Comment by ibuclaw** [comment]
The Z side is a provider network.

To circle back round to this comment https://github.com/netbox-community/netbox-topology-views/issues/590#issuecomment-2580079555

https://github.com/netbox-community/netbox-topology-views/blob/cf8641939a1dbbef4fa73516d0e735326aefcb11/netbox_topology_views/views.py#L446-L453

I think this should instead be:
```
 elif circuit_termination._provider_network is not None: 
     if ( 
         circuit_termination._provider_network_id 
         not in nodes_provider_networks 
     ): 
         nodes_provider_networks[ 
             circuit_termination._provider_network.pk 
         ] = circuit_termination._provider_network 
```

Saying that, I don't see `nodes_provider_networks` being referenced anywhere else, is this a half implemented feature (#454)?

**Comment by MFisherIT** [comment]
After upgrading Netbox from 4.0.9 to 4.2.1 and Topology Views from 4.0.9 to 4.2.0
I am having the same error. I _may_ have had the same error after the Netbox upgrade, but before updating Topology Views.

> <class 'AttributeError'>
> 'CircuitTermination' object has no attribute 'provider_network'
> Python version: 3.12.8
> NetBox version: 4.2.1
> Plugins: 
>   netbox_topology_views: 4.2.0

The same workaround @ibuclaw mentioned works for me.
No, only Z side of the circuit is terminated on an interface.

> Circuit: "63.VLXP.931492..CBCL"
> Termination side: A
> Termination type: Circuits > Provider Network
> Provider Network: "Internet"
> Marked connected: False

> Termination side: Z
> Termination type: DCIM > Location
> Provider Network: "Main Office"
> Marked connected: False
> Port speed: 80000
> Upstream speed: 80000

> Connection:
>> A side
>> Device: "MEN_deviceName_"
>> Interface: eth0

>> B Side
>> type: Circuit Termination
>> Circuit "63.VLXP.931492..CBCL"
>> Side: "63.VLXP.931492..CBCL: Termination Z"
>> Status: Connected

Below is a cable trace related to the Circuit.
![image](https://github.com/user-attachments/assets/37f70e1a-bb48-4e38-87da-d341dd186b2e)

NetBox release 	NetBox Community v4.2.1 (2025-01-08)
Python version 	3.12.8
Django version 	5.1.4
PostgreSQL version 	PostgreSQL 13.18 on x86_64-redhat-linux-gnu, compiled by gcc
Database name 	netbox
Database size 	30 MB
RQ workers 	1 (default queue)
System time 	2025-01-11 03:28:33 UTC

**Comment by MFisherIT** [comment]
Also and issue with all other termination types.
There is an error is the termination is not connected and the location, site, region is not empty.
There is no error is the termination is not connected and the location, site, region is are empty.

**Comment by MFisherIT** [comment]
With [NetBox v4.2](https://netboxlabs.com/docs/netbox/en/stable/models/circuits/circuittermination/) the "Termination" field replaced the "site" and "provider_network" fields.

**Comment by antkachenko** [comment]
Also have this issue with Netbox 4.2.2

**Comment by Andres1357** [comment]
I also have this issue. Seems a change in NetBox's `circuits.CircuitTermination` model is the root cause and this plugin needs to be updated to account for that.

See: Breaking Changes at [Release v4.2.0](https://github.com/netbox-community/netbox/releases/tag/v4.2.0)

> The `site` and `provider_network` foreign key fields on `circuits.CircuitTermination` have been replaced by the `termination` generic foreign key.

my complete exception:
```
<class 'AttributeError'>

'CircuitTermination' object has no attribute 'provider_network'

Python version: 3.12.3
NetBox version: 4.2.2
Plugins: 
  ...
  netbox_topology_views: 4.2.0
```

**Comment by justinharris1986** [comment]
This fixed it for me. May or may not be the proper way to do it. YMMV
in netbox_topology_views/views.py:
```
--- /root/views.py	2025-02-26 18:16:57.737106604 +0000
+++ views.py	2025-02-26 18:22:06.848666423 +0000
@@ -443,14 +443,14 @@
                 termination_b = create_circuit_termination(
                     circuit_termination.cable.b_terminations[0]
                 )
-            elif circuit_termination.provider_network is not None:
+            elif circuit_termination.termination is not None:
                 if (
-                    circuit_termination.provider_network_id
+                    circuit_termination.termination_id
                     not in nodes_provider_networks
                 ):
                     nodes_provider_networks[
-                        circuit_termination.provider_network.pk
-                    ] = circuit_termination.provider_network
+                        circuit_termination.termination.pk
+                    ] = circuit_termination.termination

             if bool(termination_a) and bool(termination_b):
                 circuit_model = {
```

**Comment by ibuclaw** [comment]
@mattieserver there's a couple patches here, any chance of picking one?

**Comment by arcticash** [comment]
I've just ran into this issue in the updated version of the plugin (v4.2.1) on Netbox v4.2.7, are there plans to implement one of these fixes in the next release as it seems to have been overlooked on this one!

**Comment by mories76** [comment]
I was about to submit a PR but saw that this issue doesn't have a label accepted.

**Comment by dreng** [comment]
> I was about to submit a PR but saw that this issue doesn't have a label accepted.

No problem. I'll assign you to this bug.

**Comment by algreat** [comment]
I am still getting this error on Netbox 4.2.7 and Topology View on 4.2.1. I tried setting "Show Circuit Terminations" to off but that still does not help. 

<class 'AttributeError'>

'CircuitTermination' object has no attribute 'provider_network'

Python version: 3.12.3
NetBox version: 4.2.7
Plugins: 
  netbox_bgp: 0.15.0
  netbox_floorplan: 0.6.0
  netbox_inventory: 2.3.0
  netbox_topology_views: 4.2.1

**Comment by dreng** [comment]
> I am still getting this error on Netbox 4.2.7 and Topology View on 4.2.1.

Of cause you do since it hasn't been fixed in v4.2.1. Try to upgrade to 4.3.0 which has been released today.
