### ISSUE TITLE
not liking 3.2: 'badge' received unexpected keyword argument 'bg_class'

### ISSUE THREAD

**Issue by grinapo** [mattieserver/netbox-topology-views#97]
```
<class 'django.template.exceptions.TemplateSyntaxError'>

'badge' received unexpected keyword argument 'bg_class'

Python version: 3.9.2
NetBox version: 3.2.0
```

**Comment by ekrichbaum** [comment]
"pip install netbox-topology-views --upgrade --pre" to switch to the prerelease version until the final releases.

**Comment by mattieserver** [comment]
Yeah, will do a full release on Monday.
For now the pre-release can be used.

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by grinapo** [comment]
I have simply removed the bg_class from the html ;-) 
Thanks!

**Comment by mattieserver** [comment]
https://github.com/mattieserver/netbox-topology-views/releases/tag/v1.1.0 was released to work with netbox 3.2
